# Generated by Django 4.2.7 on 2026-01-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0007_member_def_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pop_up1',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップ1'),
        ),
    ]
