# Generated by Django 4.2.7 on 2025-03-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0008_alter_member_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator_data',
            name='pop_up1',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップ1'),
        ),
        migrations.AlterField(
            model_name='administrator_data',
            name='pop_up2',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップ2'),
        ),
        migrations.AlterField(
            model_name='administrator_data',
            name='pop_up3',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップ3'),
        ),
        migrations.AlterField(
            model_name='administrator_data',
            name='pop_up4',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップ4'),
        ),
        migrations.AlterField(
            model_name='administrator_data',
            name='pop_up5',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップ5'),
        ),
        migrations.AlterField(
            model_name='member',
            name='pop_up1',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップ1'),
        ),
        migrations.AlterField(
            model_name='member',
            name='pop_up2',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップ2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='pop_up3',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップ3'),
        ),
        migrations.AlterField(
            model_name='member',
            name='pop_up4',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップ4'),
        ),
        migrations.AlterField(
            model_name='member',
            name='pop_up5',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップ5'),
        ),
    ]
