# Generated by Django 4.2.7 on 2026-03-24 04:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0009_alter_administrator_data_pop_up1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error')], max_length=50)),
                ('result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=10)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.IntegerField()),
                ('login_No', models.CharField(blank=True, max_length=255, null=True)),
                ('changes', jsonfield.fields.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='inquiry_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry_data',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='member',
            name='break_time5',
            field=models.CharField(default='#00000000', max_length=9, verbose_name='連1直昼休憩時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='break_time5_over1',
            field=models.CharField(default='#00000000', max_length=9, verbose_name='連1直残業休憩時間1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='break_time5_over2',
            field=models.CharField(default='#00000000', max_length=9, verbose_name='連1直残業休憩時間2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='break_time5_over3',
            field=models.CharField(default='#00000000', max_length=9, verbose_name='連1直残業休憩時間3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='break_time6',
            field=models.CharField(default='#00000000', max_length=9, verbose_name='連2直昼休憩時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='break_time6_over1',
            field=models.CharField(default='#00000000', max_length=9, verbose_name='連2直残業休憩時間1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='break_time6_over2',
            field=models.CharField(default='#00000000', max_length=9, verbose_name='連2直残業休憩時間2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='break_time6_over3',
            field=models.CharField(default='#00000000', max_length=9, verbose_name='連2直残業休憩時間3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='shop',
            field=models.CharField(choices=[('P', 'P'), ('R', 'R'), ('W1', 'W1'), ('W2', 'W2'), ('T1', 'T1'), ('T2', 'T2'), ('A1', 'A1'), ('A2', 'A2'), ('J', 'J'), ('その他', 'その他'), ('組長以上(P,R,T,その他)', '組長以上(P,R,T,その他)'), ('組長以上(W,A)', '組長以上(W,A)'), ('異動・退社', '異動・退社')], max_length=15, verbose_name='ショップ'),
        ),
        migrations.CreateModel(
            name='Operation_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_no4', models.IntegerField(verbose_name='従業員番号')),
                ('post_page', models.CharField(blank=True, null=True, verbose_name='ページ')),
                ('operation_models', models.CharField(blank=True, null=True, verbose_name='編集したモデル')),
                ('status', models.CharField(blank=True, null=True, verbose_name='結果')),
                ('operation_detail', models.TextField(blank=True, null=True, verbose_name='編集詳細')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kosu.member', verbose_name='氏名')),
            ],
        ),
    ]
