# Generated by Django 4.2.7 on 2025-04-02 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0010_asynctask'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry_data',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Operation_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_no4', models.IntegerField(verbose_name='従業員番号')),
                ('operation_models', models.CharField(blank=True, null=True, verbose_name='編集したモデル')),
                ('operation_detail', models.TextField(blank=True, null=True, verbose_name='編集詳細')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kosu.member', verbose_name='氏名')),
            ],
        ),
    ]
