# Generated by Django 4.2.7 on 2025-04-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0011_inquiry_data_created_at_inquiry_data_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_history',
            name='post_page',
            field=models.CharField(blank=True, null=True, verbose_name='ページ'),
        ),
        migrations.AddField(
            model_name='operation_history',
            name='status',
            field=models.CharField(blank=True, null=True, verbose_name='結果'),
        ),
    ]
