# Generated by Django 4.2.7 on 2025-05-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0012_operation_history_post_page_operation_history_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='break_time5',
            field=models.CharField(default='#10401130', max_length=9, verbose_name='連1直昼休憩時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='break_time5_over1',
            field=models.CharField(default='#00000000', max_length=9, verbose_name='連1直残業休憩時間1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='break_time5_over2',
            field=models.CharField(default='#00000000', max_length=9, verbose_name='連1直残業休憩時間2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='break_time5_over3',
            field=models.CharField(default='#00000000', max_length=9, verbose_name='連1直残業休憩時間3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='break_time6',
            field=models.CharField(default='#21202210', max_length=9, verbose_name='連2直昼休憩時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='break_time6_over1',
            field=models.CharField(default='#00000000', max_length=9, verbose_name='連2直残業休憩時間1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='break_time6_over2',
            field=models.CharField(default='#00000000', max_length=9, verbose_name='連2直残業休憩時間2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='break_time6_over3',
            field=models.CharField(default='#00000000', max_length=9, verbose_name='連2直残業休憩時間3'),
            preserve_default=False,
        ),
    ]
