# Generated by Django 4.2.7 on 2025-12-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0013_member_break_time5_member_break_time5_over1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=10)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.IntegerField()),
                ('session_data', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
