# Generated by Django 4.2.7 on 2025-12-11 03:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0014_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='session_data',
            new_name='login_No',
        ),
        migrations.AddField(
            model_name='history',
            name='changes',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
